### ISSUE TITLE
Can I fork the plugin to Nikola?

### ISSUE THREAD

**Issue by ivanteoh** [noirbizarre/pelican-microdata#1]
@noirbizarre Can I fork the plugin to [getnikola/nikola](https://github.com/getnikola/nikola)? I will rename `plugin.py` to `microdata.py` and put your name in the author field in `microdata.plugin` for this plugin. Is that ok?

**Comment by noirbizarre** [comment]
Hi !

Yes you can fork it.
I plan to add some feature in a near future (I didn't had time until now), so I will let you handle the merges (or maybe I will do some pull-requests).

**Comment by ivanteoh** [comment]
FYI, the plugin is at https://github.com/getnikola/plugins/tree/master/v7/microdata.
